// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: meshmesh/meshmesh.proto

package meshmesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Meshmesh_SayHello_FullMethodName = "/meshmesh.Meshmesh/SayHello"
)

// MeshmeshClient is the client API for Meshmesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type MeshmeshClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type meshmeshClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshmeshClient(cc grpc.ClientConnInterface) MeshmeshClient {
	return &meshmeshClient{cc}
}

func (c *meshmeshClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Meshmesh_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshmeshServer is the server API for Meshmesh service.
// All implementations must embed UnimplementedMeshmeshServer
// for forward compatibility.
//
// The greeting service definition.
type MeshmeshServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedMeshmeshServer()
}

// UnimplementedMeshmeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshmeshServer struct{}

func (UnimplementedMeshmeshServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMeshmeshServer) mustEmbedUnimplementedMeshmeshServer() {}
func (UnimplementedMeshmeshServer) testEmbeddedByValue()                  {}

// UnsafeMeshmeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshmeshServer will
// result in compilation errors.
type UnsafeMeshmeshServer interface {
	mustEmbedUnimplementedMeshmeshServer()
}

func RegisterMeshmeshServer(s grpc.ServiceRegistrar, srv MeshmeshServer) {
	// If the following call pancis, it indicates UnimplementedMeshmeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Meshmesh_ServiceDesc, srv)
}

func _Meshmesh_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Meshmesh_ServiceDesc is the grpc.ServiceDesc for Meshmesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meshmesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meshmesh.Meshmesh",
	HandlerType: (*MeshmeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Meshmesh_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meshmesh/meshmesh.proto",
}
