// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: meshmesh/meshmesh.proto

package meshmesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Meshmesh_SayHello_FullMethodName     = "/meshmesh.Meshmesh/SayHello"
	Meshmesh_NodeInfo_FullMethodName     = "/meshmesh.Meshmesh/NodeInfo"
	Meshmesh_NodeReboot_FullMethodName   = "/meshmesh.Meshmesh/NodeReboot"
	Meshmesh_BindClear_FullMethodName    = "/meshmesh.Meshmesh/BindClear"
	Meshmesh_SetTag_FullMethodName       = "/meshmesh.Meshmesh/SetTag"
	Meshmesh_SetChannel_FullMethodName   = "/meshmesh.Meshmesh/SetChannel"
	Meshmesh_NetworkNodes_FullMethodName = "/meshmesh.Meshmesh/NetworkNodes"
)

// MeshmeshClient is the client API for Meshmesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type MeshmeshClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error)
	NodeReboot(ctx context.Context, in *NodeRebootRequest, opts ...grpc.CallOption) (*NodeRebootReply, error)
	BindClear(ctx context.Context, in *BindClearRequest, opts ...grpc.CallOption) (*BindClearReply, error)
	SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*SetTagReply, error)
	SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*SetChannelReply, error)
	NetworkNodes(ctx context.Context, in *NetworkNodesRequest, opts ...grpc.CallOption) (*NetworkNodesReply, error)
}

type meshmeshClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshmeshClient(cc grpc.ClientConnInterface) MeshmeshClient {
	return &meshmeshClient{cc}
}

func (c *meshmeshClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Meshmesh_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoReply)
	err := c.cc.Invoke(ctx, Meshmesh_NodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) NodeReboot(ctx context.Context, in *NodeRebootRequest, opts ...grpc.CallOption) (*NodeRebootReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRebootReply)
	err := c.cc.Invoke(ctx, Meshmesh_NodeReboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) BindClear(ctx context.Context, in *BindClearRequest, opts ...grpc.CallOption) (*BindClearReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindClearReply)
	err := c.cc.Invoke(ctx, Meshmesh_BindClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) SetTag(ctx context.Context, in *SetTagRequest, opts ...grpc.CallOption) (*SetTagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTagReply)
	err := c.cc.Invoke(ctx, Meshmesh_SetTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*SetChannelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetChannelReply)
	err := c.cc.Invoke(ctx, Meshmesh_SetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshmeshClient) NetworkNodes(ctx context.Context, in *NetworkNodesRequest, opts ...grpc.CallOption) (*NetworkNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkNodesReply)
	err := c.cc.Invoke(ctx, Meshmesh_NetworkNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshmeshServer is the server API for Meshmesh service.
// All implementations must embed UnimplementedMeshmeshServer
// for forward compatibility.
//
// The greeting service definition.
type MeshmeshServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error)
	NodeReboot(context.Context, *NodeRebootRequest) (*NodeRebootReply, error)
	BindClear(context.Context, *BindClearRequest) (*BindClearReply, error)
	SetTag(context.Context, *SetTagRequest) (*SetTagReply, error)
	SetChannel(context.Context, *SetChannelRequest) (*SetChannelReply, error)
	NetworkNodes(context.Context, *NetworkNodesRequest) (*NetworkNodesReply, error)
	mustEmbedUnimplementedMeshmeshServer()
}

// UnimplementedMeshmeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshmeshServer struct{}

func (UnimplementedMeshmeshServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMeshmeshServer) NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeInfo not implemented")
}
func (UnimplementedMeshmeshServer) NodeReboot(context.Context, *NodeRebootRequest) (*NodeRebootReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeReboot not implemented")
}
func (UnimplementedMeshmeshServer) BindClear(context.Context, *BindClearRequest) (*BindClearReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindClear not implemented")
}
func (UnimplementedMeshmeshServer) SetTag(context.Context, *SetTagRequest) (*SetTagReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTag not implemented")
}
func (UnimplementedMeshmeshServer) SetChannel(context.Context, *SetChannelRequest) (*SetChannelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetChannel not implemented")
}
func (UnimplementedMeshmeshServer) NetworkNodes(context.Context, *NetworkNodesRequest) (*NetworkNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkNodes not implemented")
}
func (UnimplementedMeshmeshServer) mustEmbedUnimplementedMeshmeshServer() {}
func (UnimplementedMeshmeshServer) testEmbeddedByValue()                  {}

// UnsafeMeshmeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshmeshServer will
// result in compilation errors.
type UnsafeMeshmeshServer interface {
	mustEmbedUnimplementedMeshmeshServer()
}

func RegisterMeshmeshServer(s grpc.ServiceRegistrar, srv MeshmeshServer) {
	// If the following call pancis, it indicates UnimplementedMeshmeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Meshmesh_ServiceDesc, srv)
}

func _Meshmesh_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_NodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).NodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_NodeReboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).NodeReboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_NodeReboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).NodeReboot(ctx, req.(*NodeRebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_BindClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).BindClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_BindClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).BindClear(ctx, req.(*BindClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_SetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).SetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_SetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).SetTag(ctx, req.(*SetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_SetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).SetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_SetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).SetChannel(ctx, req.(*SetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meshmesh_NetworkNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshmeshServer).NetworkNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meshmesh_NetworkNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshmeshServer).NetworkNodes(ctx, req.(*NetworkNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Meshmesh_ServiceDesc is the grpc.ServiceDesc for Meshmesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meshmesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meshmesh.Meshmesh",
	HandlerType: (*MeshmeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Meshmesh_SayHello_Handler,
		},
		{
			MethodName: "NodeInfo",
			Handler:    _Meshmesh_NodeInfo_Handler,
		},
		{
			MethodName: "NodeReboot",
			Handler:    _Meshmesh_NodeReboot_Handler,
		},
		{
			MethodName: "BindClear",
			Handler:    _Meshmesh_BindClear_Handler,
		},
		{
			MethodName: "SetTag",
			Handler:    _Meshmesh_SetTag_Handler,
		},
		{
			MethodName: "SetChannel",
			Handler:    _Meshmesh_SetChannel_Handler,
		},
		{
			MethodName: "NetworkNodes",
			Handler:    _Meshmesh_NetworkNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meshmesh/meshmesh.proto",
}
